# These are supported funding model platforms

# github: [youlookwhat]
custom: [https://raw.githubusercontent.com/youlookwhat/CloudReader/master/file/Wechat-admire.jpg，https://raw.githubusercontent.com/youlookwhat/CloudReader/master/file/alipay-admire.jpg]
